Bump actions/checkout from 3 to 4 (#1070)
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/vuln-check.yaml b/.github/workflows/vuln-check.yaml
--- a/.github/workflows/vuln-check.yaml
+++ b/.github/workflows/vuln-check.yaml
@@ -8,6 +8,11 @@ on:
         required: true
         type: string
         default: 'main'
+      find-latest-release:
+        description: 'Flag to find the latest version for specified `target-ref`'
+        required: false
+        type: boolean
+        default: false
     secrets:
       CR_PAT:
         required: true
@@ -20,10 +25,39 @@ jobs:
   docker:
     runs-on: ubuntu-latest
 
+    env:
+      GH_TOKEN: ${{ secrets.CR_PAT }}
+
     steps:
-      - uses: actions/checkout@v3
+      # This first checkout is needed to use `ci/vuln-check/*`
+      - uses: actions/checkout@v4
+
+      - id: prepare-target-ref
+        name: Prepare target-ref
+        run: |
+          # Find the latest release name if `find-latest-release` is set to true. Use the value of `target-ref` as is otherwise.
+          if [[ ${{ inputs.find-latest-release }} = 'true' ]]; then
+            releases=$(ci/vuln-check/fetch_gh_releases "${{ github.event.repository.owner.login }}" "${{ github.event.repository.name }}")
+            echo -------------
+            echo "releases: $releases"
+            echo -------------
+            target_release=''
+            if [[ -n $releases ]]; then
+              target_release=$(ci/vuln-check/find_latest_release "${{ inputs.target-ref }}" $releases)
+            fi
+            if [[ -z $target_release ]]; then
+              echo "Can't find a target release"
+              exit 1
+            fi
+            echo $target_release
+            echo "target-ref=$target_release" >> $GITHUB_OUTPUT
+          else
+            echo "target-ref=${{ inputs.target-ref }}" >> $GITHUB_OUTPUT
+          fi
+
+      - uses: actions/checkout@v4
         with:
-          ref: ${{ inputs.target-ref }}
+          ref: ${{ steps.prepare-target-ref.outputs.target-ref }}
 
       - name: Set up JDK 8
         uses: actions/setup-java@v3
@@ -33,7 +67,7 @@ jobs:
 
       - name: Login to GitHub Container Registry
         if: always()
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
@@ -74,7 +108,7 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": ":octagonal_sign: The vulnerability check for ScalarDB Server on `${{ github.repository }}` <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|failed> with `${{ inputs.target-ref }}`"
+                    "text": ":octagonal_sign: The vulnerability check for ScalarDB Server on `${{ github.repository }}` <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|failed> with `${{ steps.prepare-target-ref.outputs.target-ref }}`"
                   }
                 }
               ]
@@ -105,7 +139,7 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": ":octagonal_sign: The vulnerability check for ScalarDB Schema Loader on `${{ github.repository }}` <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|failed> with `${{ inputs.target-ref }}`"
+                    "text": ":octagonal_sign: The vulnerability check for ScalarDB Schema Loader on `${{ github.repository }}` <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|failed> with `${{ steps.prepare-target-ref.outputs.target-ref }}`"
                   }
                 }
               ]
@@ -113,4 +147,3 @@ jobs:
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SECURITY_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
-
